#!/bin/bash
# Generates YandexOAuthSecrets.generated.swift from env vars (CI) or Secrets.xcconfig (local)
# Run as Xcode Run Script phase before Compile Sources

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="${SRCROOT:-$SCRIPT_DIR/..}/ScreenShoter/YandexOAuthSecrets.generated.swift"
SECRETS_XCCONFIG="${SRCROOT:-$SCRIPT_DIR/..}/ScreenShoter/Secrets.xcconfig"

CLIENT_ID=""
CLIENT_SECRET=""

if [ -n "$YANDEX_CLIENT_ID" ] && [ -n "$YANDEX_CLIENT_SECRET" ]; then
  # CI: use environment variables from GitHub Secrets
  CLIENT_ID="$YANDEX_CLIENT_ID"
  CLIENT_SECRET="$YANDEX_CLIENT_SECRET"
elif [ -f "$SECRETS_XCCONFIG" ]; then
  # Local: parse Secrets.xcconfig (skip comments, handle KEY = value)
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%%//*}"
    line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    [ -z "$line" ] && continue
    if [[ "$line" == *=* ]]; then
      key="${line%%=*}"
      key=$(echo "$key" | sed 's/[[:space:]]*$//')
      value="${line#*=}"
      value=$(echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      case "$key" in
        YANDEX_CLIENT_ID) CLIENT_ID="$value" ;;
        YANDEX_CLIENT_SECRET) CLIENT_SECRET="$value" ;;
      esac
    fi
  done < "$SECRETS_XCCONFIG"
fi

# Escape backslashes and quotes for Swift string literal
escape_swift() {
  printf '%s' "$1" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g'
}
CLIENT_ID_ESC=$(escape_swift "$CLIENT_ID")
CLIENT_SECRET_ESC=$(escape_swift "$CLIENT_SECRET")

mkdir -p "$(dirname "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" << EOF
// Auto-generated by scripts/generate-oauth-secrets.sh — do not edit
// Values from YANDEX_CLIENT_ID/YANDEX_CLIENT_SECRET (CI) or ScreenShoter/Secrets.xcconfig (local)
import Foundation

enum YandexOAuthSecrets {
    static let clientID = "$CLIENT_ID_ESC"
    static let clientSecret = "$CLIENT_SECRET_ESC"
}
EOF
